### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [guicho271828/dataloader#2]
Building with SBCL 2.0.5 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id abd5e4f6b0a975bd9cb0810b3173e1033fac727c

*dataloader.test* fails to build with the following error:

```
; caught ERROR:
;   (during macroexpansion of (UIOP/PACKAGE:DEFINE-PACKAGE :DATALOADER ...))
;   unrecognized define-package keyword :LOCAL-NICKNAMES
...
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A10083}>: The name "DATALOADER" does not designate any package.

```

*dataloader* fails to build with the following error:

```
; caught ERROR:
;   (during macroexpansion of (UIOP/PACKAGE:DEFINE-PACKAGE :DATALOADER ...))
;   unrecognized define-package keyword :LOCAL-NICKNAMES
...
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A10083}>: The name "DATALOADER" does not designate any package.

```

[Full log here](http://report.quicklisp.org/2021-03-16/failure-report/dataloader.html)

**Comment by guicho271828** [comment]
Oh, so quicklisp does not currently support sbcl versions that have `:LOCAL-NICKNAMES` available?

**Comment by guicho271828** [comment]
and asdf versions

**Comment by guicho271828** [comment]
uiop:define-package supports local-nicknames only in later versions of asdf.

**Comment by guicho271828** [comment]
I stopped using define-package, this should fix it.
